name: Run Tests PR

on:
  pull_request:
    branches: [ main ]
    paths-ignore: [ '.gitignore', '.swift-format', 'README.md', 'LICENSE' ]

jobs:
  run_tests_pr:
    runs-on: macos-latest
    steps:
    - name: Checkout project including tags
      uses: actions/checkout@v3
    - name: Set Swift version to same as Swift Playgrounds
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6"
    - name: Run tests
      run: swift test

