name: Run Tests

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'README.md', '.gitignore' ]

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - name: Checkout project including tags
      uses: actions/checkout@v3
    - name: Set Swift version to same as Swift Playgrounds
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6"
    - name: Run tests
      run: swift test -v

