name: Swift

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'README.md', '.gitignore' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ 'README.md', '.gitignore' ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout project including tags
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set Swift version to same as Swift Playgrounds
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6"
    - name: Run tests
      run: swift test -v
    - name: Get next version
      id: get-next-version
      uses: paulhatch/semantic-version@v5.0.0-alpha2
      with:
        tag_prefix: ""
        change_path: "Sources Package.swift .github"
        search_commit_body: false
    - name: Create tag
      uses: actions/github-script@v5
      if: ${{ steps.get-next-version.outputs.changed == 'true' }}
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.get-next-version.outputs.version_tag }}",
            sha: context.sha
          })

