name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "// swift-tools-version:5.6"
        replace: "// swift-tools-version:5.5"
        regex: false
        include: "Package.swift"
    - name: Run tests
      run: swift test -v
