name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Find and Replace
      uses: visiosto/replace-value@v1.2.1
      with:
        file: "Package.swift"
        value: "swift-tools-version:5.6"
        replaced: "swift-tools-version:5.5"
    - name: Run tests
      run: swift test -v
