name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6"
    # - name: Set swift tools version for test
    #   run: |
    #     cat Package.swift
    #     sed -I '' 's/swift-tools-version:5.6/swift-tools-version:5.5/' Package.swift
    #     cat Package.swift
    - name: Run tests
      run: swift test -v
