name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6"
    - name: Run tests
      run: swift test -v
    - uses: paulhatch/semantic-version@v5.0.0-alpha2
      with:
        tag_prefix: ""
        change_path: "Sources Package.swift .github"
        search_commit_body: false

